import { ReactLenis } from "lenis/react";

export const metadata = {
  title: 'Enigma 3D logo',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <ReactLenis root>

    <html lang="en">
      <body>{children}</body>
    </html>
    </ReactLenis>
  )
}
